//@flow
export const USER_STATE_CHANGE = 'USER_STATE_CHANGE';
export const USER_SERVICES_STATE_CHANGE = 'USER_POSTS_STATE_CHANGE';
export const ALL_USER_SERVICES_STATE_CHANGE = 'ALL_USER_POSTS_STATE_CHANGE';
