//@flow
export const USER_STATE_CHANGE = 'USER_STATE_CHANGE';
export const USER_SERVICES_STATE_CHANGE = 'USER_SERVICES_STATE_CHANGE';
export const ALL_USER_SERVICES_STATE_CHANGE = 'ALL_USER_POSTS_STATE_CHANGE';
export const CLEAR_DATA = 'CLEAR_DATA';
export const USERS_DATA_STATE_CHANGE = 'USERS_DATA_STATE_CHANGE'
export const USERS_SERVICES_STATE_CHANGE = 'USERS_SERVICES_STATE_CHANGE';
